# Generated by Django 5.0.1 on 2024-03-09 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goOutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='emprendimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contacto', to='goOutApp.emprendimiento'),
        ),
        migrations.AlterField(
            model_name='sobrenos',
            name='emprendimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sobreNos', to='goOutApp.emprendimiento'),
        ),
    ]
