# Generated by Django 5.0.3 on 2024-03-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goOutApp', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='clientes_favoritos', to='goOutApp.emprendimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goOutApp.cliente')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='goOutApp.evento')),
            ],
        ),
    ]
