# Generated by Django 5.0.3 on 2024-03-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goOutApp', '0004_cliente_favoritos_alter_cliente_telefono_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='favoritos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.TextField(max_length=20),
        ),
    ]
